<div class="container">
    <div class="divider"><hr style="opacity: 0.1"></div>
    <div class="row">                
        <div class="col-md-6">
            All rights reserved. Copyright &copy; <?php echo date('Y') ?>
            <a href="<?=$this->url('home')?>">
                <?php echo "Iligan Access Institute of Technology, Inc."?>
            </a>
        </div>
        <div class="cold-md-6">
            <span class="pull-right">
                Developed by: <a href="http://www.gabbydgab.com" target="_blank">Gab Amba</a>                            
            </span>
        </div>
    </div>
</div>