<?php 
    $this->headTitle('Student Admission');
    
//    $this->headLink()->prependStylesheet($this->basePath('assets/datatables/datatables.min.css'));
//    $this->inlineScript()
//        ->prependFile($this->basePath('assets/datatables/datatables.min.js'))
//        ->prependFile($this->basePath('assets/datatables/datatables-buttons.js'));
?>
<section class="content-header">
    <h1>
      Student Admission
      <small>Enlisting of new student</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo$this->url('home'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"> Student Admission </li>
    </ol>
</section>
<div class="divider"><br></div>       
<section class="content">
<?php
    $form = $this->studentForm();
    $fname = $form->get('first_name');
    $mname = $form->get('middle_name');
    $lname = $form->get('last_name');
    $form->prepare();
    echo $this->form()->openTag($form); 
?> 
    <fieldset>
        <div class="form-group">
            <?php echo $this->formLabel($fname) ?>
            <?php echo $this->formElement($fname) ?>
            <?php echo $this->formElementErrors()->render($fname, ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($mname) ?>
            <?php echo $this->formElement($mname) ?>
            <?php echo $this->formElementErrors()->render($mname, ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($lname) ?>
            <?php echo $this->formElement($lname) ?>
            <?php echo $this->formElementErrors()->render($lname, ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>    
    </fieldset>
<?php echo $this->form()->closeTag(); ?>
</section>