<?php     
    $this->headTitle('Student Master List');
    
//    $this->headLink()->prependStylesheet('/assets/datatables/datatables.min.css');
//    $this->inlineScript()
//        ->prependFile('/assets/datatables/datatables.min.js')
//        ->prependFile('/assets/datatables/Buttons-1.2.2/js/buttons.bootstrap.min.js');
?>
<section class="content-header">
    <h1>
      Training, Assessment, Certification and Employment Report
      <small>TESDA Mothly Report</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('home'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"> TESDA Report </li>
    </ol>
</section>
<div class="divider"><br></div>       
<section class="content">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        <small>As of <?php echo date('m') . "," . date('Y');?></small>
                    </h2>
                </div>
                <div class="clearfix"></div>
                <div class="x_content table-responsive">
                    <table id="datatable-buttons" class="table table-hover table-bordered">
                      <thead>
                        <tr>
                          <th>ID Number</th>
                          <th>First Name</th>
                          <th>Middle Initial</th>
                          <th>Last Name</th>
                          <th>Sex</th>
                          <th>Date of Birth</th>
                          <th>Civil Status</th>
                          <th>Nationality</th>
                          <th>Scholarship</th>
                          <th>Graduate</th>
                        </tr>
                      </thead>
                      <tbody>
                            <?php foreach ($this->students() as $student) : ?>
                                <tr>
                                    <td><?=$student->studentId()?></td>
                                    <td><?=$student->firstName()?></td>
                                    <td><?= substr($student->middleName(), 0, 1)?></td>
                                    <td><?=$student->lastName()?></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            <?php endforeach; ?>
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>