<?php 

/**
 * @todo Clean-up the logic
 */
    $this->headTitle('Student Admission');

    $first_name_has_error = '';
    $middle_name_has_error = '';
    $last_name_has_error = '';
    $birthdate_has_error = '';
    $number_has_error = '';

    $form   = $this->studentForm();
    $form->setAttribute('action', $this->url());

    $submit = $form->get('submit');
    $submit->setAttribute('value', "Add");
    $submit->setAttribute('class', "btn btn-primary pull-right");
    $first_name = $form->get('first_name');
    $middle_name = $form->get('middle_name');
    $last_name = $form->get('last_name');
    $birthdate = $form->get('birthdate');
    $contact_number = $form->get('contact_number');
    
    
    if (isset($this->currentData)) {
        $first_name->setValue($this->currentData['first_name']);
        $middle_name->setValue($this->currentData['middle_name']);
        $last_name->setValue($this->currentData['last_name']);
        $birthdate->setValue($this->currentData['birthdate']);
        $contact_number->setValue($this->currentData['contact_number']);
        
        if (isset($this->validationErrors['first_name'])) {
            $first_name_has_error = 'has-error';
            $first_name->setMessages([$this->validationErrors['first_name']]);
        }
        
        if (isset($this->validationErrors['middle_name'])) {
            $middle_name_has_error = 'has-error';
            $middle_name->setMessages([$this->validationErrors['middle_name']]);
        }
        
        if (isset($this->validationErrors['last_name'])) {
            $last_name_has_error = 'has-error';
            $last_name->setMessages([$this->validationErrors['last_name']]);    
        }

        if (isset($this->validationErrors['birthdate'])) {
            $birthdate_has_error = 'has-error';
            $birthdate->setMessages([$this->validationErrors['birthdate']]);    
        }

        if (isset($this->validationErrors['contact_number'])) {
            $number_has_error = 'has-error';
            $contact_number->setMessages([$this->validationErrors['contact_number']]);    
        }
    }
    
    $form->prepare();
?>
<section class="content-header">
    <h1>
      Enrollment Form
      <small>Information provided will be registered as permanent record.</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo$this->url('home'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"> Student Admission </li>
    </ol>
</section>
<div class="divider"><br></div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            <?php if (isset($this->message)) : ?>
            <blockquote class="text-success">
                <p><?php echo $this->message; ?></p>
            </blockquote>
            <?php endif; ?>
            <?php if (isset($this->error_message)) : ?>
            <blockquote class="text-danger">
                <p><?php echo $this->error_message; ?></p>
            </blockquote>
            <?php endif; ?>
            <?php echo $this->form()->openTag($form); ?> 
                <fieldset>
                    <legend>Personal Information:</legend>
                    <!--
                    <div class="form-group">
                        <?php // echo $this->formLabel($form->get('student_id')) ?>
                        <?php // echo $this->formElementErrors()->render($form->get('student_id'), ['class' => 'help-block']) ?>
                        <?php // echo $this->formElement($form->get('student_id')) ?>                        
                    </div>
                    -->
                    <div class="form-group <?php echo $first_name_has_error;?>">
                        <?php echo $this->formLabel($first_name) ?>
                        <?php echo $this->formElementErrors()->render($first_name, ['class' => 'help-block']) ?>
                        <?php echo $this->formElement($first_name) ?>                        
                    </div>
                    <div class="form-group <?php echo $middle_name_has_error;?>">
                        <?php echo $this->formLabel($middle_name) ?>
                        <?php echo $this->formElementErrors()->render($middle_name, ['class' => 'help-block']) ?>
                        <?php echo $this->formElement($middle_name) ?>                        
                    </div>
                    <div class="form-group <?php echo $last_name_has_error;?>">
                        <?php echo $this->formLabel($last_name) ?>
                        <?php echo $this->formElement($last_name) ?>
                        <?php echo $this->formElementErrors()->render($last_name, ['class' => 'help-block']) ?>
                    </div>
                    
                    <div class="form-group <?php echo $birthdate_has_error;?>">
                        <?php echo $this->formLabel($birthdate) ?>
                        <?php echo $this->formElementErrors()->render($birthdate, ['class' => 'help-block']) ?>
                        <?php echo $this->formElement($birthdate) ?>                        
                    </div>
                    
                    <div class="form-group <?php echo $number_has_error;?>">
                        <?php echo $this->formLabel($contact_number) ?>
                        <?php echo $this->formElementErrors()->render($contact_number, ['class' => 'help-block']) ?>
                        <?php echo $this->formElement($contact_number) ?>                        
                    </div>                       
                </fieldset>
                <!-- 
                <fieldset>
                    <legend>Educational Background:</legend>
                </fieldset>
                -->
                <div class="form-group">
                    <?php echo $this->formElement($submit); ?>
                </div> 
            <?php echo $this->form()->closeTag(); ?>
            <div class="divider"><hr></div>
        </div>
        <div class="col-md-3">
            
        </div>
    </div>
</section>