
<section class="content-header">
    <h1>
      Official Transcript of Record
      <small>Student Permanent Record</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo$this->url('home'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"> Student Admission </li>
    </ol>
</section>
<div class="divider"><br></div>
<section class="content">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="row">
                    <i style="font-size: 20px;">Last Name</i>
                </div>
                <div class="row">
                    <strong style="font-size: 30px"><?php echo $student->getLastName(); ?></strong>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <i style="font-size: 20px;">First Name</i>
                </div>
                <div class="row">
                    <strong style="font-size: 30px"><?php echo $student->getFirstName(); ?></strong>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <i style="font-size: 20px;">Middle Name</i>
                </div>
                <div class="row">
                    <strong style="font-size: 30px"><?php echo $student->getMiddleName(); ?></strong>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <img src="/assets/site/images/iaccess-logo.png" class="img-responsive">
            </div>
            <div class="col-md-10">
                <div class="col-md-4">
                    <div class="row">
                        <i style="font-size: 20px;">Gender</i>
                    </div>
                    <div class="row">
                        <strong style="font-size: 30px"><?php // echo $student->middleName(); ?></strong>
                    </div>
                </div>
                <div class="col-md-8">
                    
                </div>
            </div>
        </div>
    </div>
</section>