<hr>
<div class="container">
    <h3 style="text-transform: uppercase">
        <?php echo "Iligan Access Institute of Technology, Inc."?>
        <small style="text-transform: capitalize">
            Advance Competitive Career Educational Skills System
        </small>
    </h3>
    <h4>
        <small>            
            <span>
                <i class="fa fa-map-marker">&nbsp;</i> 
                3/F Deleste Building corner Badelles Street, Pala-o, Iligan City, 9200, Philippines
            </span>
            &nbsp;|&nbsp;
            <span>
                <i class="fa fa-phone-square">&nbsp;</i> +63 (063) 223-1804
            </span>
            &nbsp;|&nbsp;
            <span>
                <i class="fa fa-phone-square">&nbsp;</i> 0926-744-5779
            </span>
            &nbsp;|&nbsp;
            <span>
                <i class="fa fa-envelope">&nbsp;</i> iliganaccess@yahoo.com
            </span>
        </small>
    </h4>
    <div class="row">
        <div class="col-md-3">            
            <img src="/assets/site/images/iaccess-icon.png" class="img-responsive center-block" width="160px">
            <h4 class="text-center">Seal of Excellence</h4>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-3">
                    <h5 class="heading">Services</h5>
                    <ul class="zeroed">
                        <li><a href="<?=$this->url('dashboard');?>">Personnel Portal</a></li>
<!--                        <li><a href="#">Student Portal</a></li>
                        <li><a href="#">Student Record Verification</a></li>                        
                        <li><a href="#">Careers</a></li>-->
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5 class="heading">Offices</h5>
                    <ul class="zeroed">
                        <li><a href="#">Office of the Registrar</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5 class="heading">Legalities</h5>
                    <ul class="zeroed">
                        <li><a href="#">Terms and Conditions</a></li>
                        <li><a href="#">Privacy Policy</a></li>                        
                        <li><a href="#">Site Map</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <div class="row">
                        <h5 class="heading text-center">Accredited By:</h5>
                        <div class="col-md-6">                    
                            <img src="/assets/site/images/tesda-logo.png" class="img-responsive center-block" width="80px">
                            <h5 class="text-center"><small>TESDA</small></h5>
                        </div>
                        <div class="col-md-6">                    
                            <img src="/assets/site/images/transparency-seal.png" class="img-responsive center-block" width="80px">
                            <h5 class="text-center"><small>DepEd</small></h5>
                        </div>
                    </div>
                </div>
            </div>            
        </div>
    </div>
</div>