<?php
    $this->headTitle('Class Schedule');   
    
//    $this->headLink()->prependStylesheet('/assets/datatables/datatables.min.css');
//    $this->inlineScript()
//        ->prependFile('/assets/datatables/datatables.min.js')
//        ->prependFile('/assets/datatables/Buttons-1.2.2/js/buttons.bootstrap.min.js');
?>
<section class="content-header">
    <h1>
      Class Schedule
      <small>List of all classes as of <?php echo date('M d, Y');?>.</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('home'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"> Class Schedule </li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-8 col-sm-8 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        <small></small>
                    </h2>
                </div>
                
                <div class="table-responsive">
                    <table class="table table-bordered table-condensed table-hover table-striped">
                        <thead>
                            <tr style="text-align: center;">
                                <th>Day</th>
                                <th>Start Time</th>
                                <th>End Time</th>
                                <th>Training Program</th>
                                <th>Class will start on:</th>
                                <th>Class will end on:</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->classes as $class) : ?>
                            <tr>
                                <td><?php echo $class['day'];?></td>
                                <td><?php echo $class['starts_at'];?></td>
                                <td><?php echo $class['ends_at'];?></td>
                                <td><?php echo $class['title'];?></td>
                                <td><?php echo $class['started_at'];?></td>
                                <td></td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4">
            
        </div>
    </div>
</section>