<section class="sidebar">
    <!-- Use Navigation Here -->
    <ul class="sidebar-menu">
        <!-- DIVIDER -->
        <li class="header">INSTITUTE SERVICES</li>
        <!-- END DIVIDER -->
        <li class="active"><a href="<?php echo $this->url('home'); ?>">
            <i class="fa fa-feed"></i> <span>General Announcements</span></a>
        </li>
        
        <!-- DIVIDER -->
        <li class="header">STUDENT SERVICES</li>
        <!-- END DIVIDER -->
        <li><a href="<?php echo $this->url('student-admission');?>">
            <i class="fa fa-user-plus"></i> <span>Student Admission</span></a>
        </li>
        <li class="treeview">
            <a href="#">
              <i class="fa fa-institution"></i>
              <span>Enroll Student</span>
              <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-gear"></i> TESDA TVET Program </a></li>
              <li><a href="#"><i class="fa fa-graduation-cap"></i> Degree Courses </a></li>
              <li><a href="#"><i class="fa fa-certificate"></i> Senior High School </a></li>              
              <li><a href="#"><i class="fa fa-cubes"></i> K TO 12 </a></li>              
            </ul>
        </li>
        
        <!-- DIVIDER -->
        <li class="header">CLASS MANAGEMENT</li>
        <!-- END DIVIDER -->
        <li><a href="#">
            <i class="fa fa-list-alt"></i> <span>Course Offering</span></a>
        </li>
        <li><a href="#">
            <i class="fa fa-calendar"></i> <span>Class Schedules</span></a>
        </li>
        
        <!-- DIVIDER -->
        <li class="header">BILLING MANAGEMENT</li>
        <!-- END DIVIDER -->        
        <li class="treeview">
            <a href="#">
              <i class="fa fa-credit-card-alt"></i>
              <span>Tuition Fees</span>
              <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-gear"></i> TESDA TVET Program </a></li>
              <li><a href="#"><i class="fa fa-graduation-cap"></i> Degree Courses </a></li>
              <li><a href="#"><i class="fa fa-certificate"></i> Senior High School </a></li>              
              <li><a href="#"><i class="fa fa-cubes"></i> K TO 12 </a></li>              
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
              <i class="fa fa-plus-circle"></i>
              <span>Miscellaneous Fees</span>
              <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-gear"></i> TESDA TVET Program </a></li>
              <li><a href="#"><i class="fa fa-graduation-cap"></i> Degree Courses </a></li>
              <li><a href="#"><i class="fa fa-certificate"></i> Senior High School </a></li>              
              <li><a href="#"><i class="fa fa-cubes"></i> K TO 12 </a></li>              
            </ul>
        </li>
    </ul>
</section>