<?php     
    $this->headTitle('Student Master List');
    
//    $this->headLink()->prependStylesheet('/assets/datatables/datatables.min.css');
   // $this->inlineScript()
     //   ->prependFile('https://cdn.datatables.net/v/bs-3.3.6/jq-2.2.3/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.12/af-2.1.2/b-1.2.2/b-colvis-1.2.2/b-html5-1.2.2/b-print-1.2.2/cr-1.3.2/fc-3.2.2/fh-3.1.2/kt-2.1.3/r-2.1.0/rr-1.1.2/sc-1.4.2/se-1.2.0/datatables.min.js')
//        ->prependFile('/assets/datatables/Buttons-1.2.2/js/buttons.bootstrap.min.js')
//        ->prependFile('/assets/datatables/Buttons-1.2.2/js/dataTables.buttons.min.js');
?>
<section class="content-header">
    <h1>
      Student Master List
      <small>List for all Graduate and Undergraduate Students</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('home'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"> Students </li>
    </ol>
</section>
<div class="divider"><br></div>
<section class="content">    
    <div class="row">
        <div class="col-md-8">
            <form method="POST" action="<?php echo $this->url('enrollment.api');?>">
                <div class="form-group">
                        <label for="student_id">Student ID</label>
                        <input type="text" class="form-control" id="student_id" name="student_id" placeholder="Student ID">

                        <label for="training_regulation_code">TVET Program</label>
                        <!--<input type="text" class="form-control" id="training_regulation_id"  name="training_regulation_id" placeholder="TVER Program">-->
                        <select name="training_regulation_code" id="training_regulation_id">
                            <?php foreach($this->tvetPrograms() as $program) : ?>
                            <option value="<?php echo $program->getId();?>"><?php echo $program->getTitle();?></option>
                            <?php endforeach; ?>
                        </select>
                </div>
                <button type="submit" class="btn btn-primary pull-right">Submit</button>
            </form>
        </div>
        <div class="col-md-4">
            
        </div>
    </div>
</section>