<?php     
    $this->headTitle('Student Master List');
//    $this->headLink()->prependStylesheet('/assets/datatables/datatables.min.css');
//    $this->inlineScript()
//        ->prependFile('/assets/datatables/datatables.min.js')
//        ->prependFile('/assets/datatables/Buttons-1.2.2/js/buttons.bootstrap.min.js');
?>
<section class="content-header">
    <h1>
      Official Transcript of Record
      <small>Student Permanent Record</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('home'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"> TESDA Report </li>
    </ol>
</section>
<section class="content">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="row">
                    <i style="font-size: 20px;">Last Name</i>
                </div>
                <div class="row">
                    <strong style="font-size: 30px"><?php echo $student->lastName(); ?></strong>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <i style="font-size: 20px;">First Name</i>
                </div>
                <div class="row">
                    <strong style="font-size: 30px"><?php echo $student->firstName(); ?></strong>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <i style="font-size: 20px;">Middle Name</i>
                </div>
                <div class="row">
                    <strong style="font-size: 30px"><?php echo $student->middleName(); ?></strong>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <img src="/assets/site/images/iaccess-logo.png" class="img-responsive">
            </div>
            <div class="col-md-10">
                <div class="col-md-4">
                    <div class="row">
                        <i style="font-size: 20px;">Gender</i>
                    </div>
                    <div class="row">
                        <strong style="font-size: 30px"><?php // echo $student->middleName(); ?></strong>
                    </div>
                </div>
                <div class="col-md-8">
                    
                </div>
            </div>
        </div>
    </div>
</section>