<?php     
    $this->headTitle('Student Master List');
//    $this->headLink()->prependStylesheet('/assets/datatables/datatables.min.css');
//    $this->inlineScript()
//        ->prependFile('/assets/datatables/datatables.min.js')
//        ->prependFile('/assets/datatables/Buttons-1.2.2/js/buttons.bootstrap.min.js');
?>
<section class="content-header">
    <h1>
      Student Master List
      <small>List of all students as of <?php echo date('M d, Y');?>.</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('home'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"> TESDA Report </li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-8 col-sm-8 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        <small></small>
                    </h2>
                </div>
                
                <div class="table-responsive">
<!--                    <table class="table table-bordered table-condensed table-hover table-striped">
                        <thead>
                            <tr style="text-align: center;">
                                <th>ID Number</th>
                                <th>Name</th>                          
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php // $student = $this->students() ; ?>
                            <tr>
                                <td style="width: 90px;"></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>-->
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4">
            
        </div>
    </div>
</section>