<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php 
            echo $this->headMeta()
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no');
            
            echo $this->headTitle("iAccess")
                ->setSeparator(' - ')
                ->setAutoEscape(false);
        
            echo $this->headLink(['rel' => 'shortcut icon', 'href' => '/assets/site/images/icons/favicon.ico'])
                ->prependStylesheet('/assets/dashboard/css/skin-blue.min.css')
                ->prependStylesheet('/assets/dashboard/css/AdminLTE.min.css')
                ->prependStylesheet('/assets/bootstrap/css/bootstrap.min.css')
                ->prependStylesheet('/assets/font-awesome/css/font-awesome.min.css');
        ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">        
        <div class="wrapper">
            <header class="main-header">
             <?php echo $this->partial('partial/navigation/header'); ?>
            </header>
            <aside class="main-sidebar">
                <?php echo $this->partial('partial/navigation/sidebar'); ?>
            </aside>
            <div class="content-wrapper">
                <?php echo $this->content; ?>
            </div>
            <footer class="main-footer">
                <?php echo $this->partial('partial/footer'); ?>         
            </footer>            
        </div>
        <?php 
            echo $this->inlineScript() //prepend up here
                //->prependFile('/assets/dashboard/js/dashboard.js') // requires ChartJs package
                ->prependFile('/assets/dashboard/js/app.min.js')
                ->prependFile('/assets/bootstrap/js/tab.js') 
                ->prependFile('/assets/bootstrap/js/bootstrap.min.js')
                ->prependFile('/assets/jquery-ui/jquery-ui.min.js')
                ->prependFile('/assets/jquery/jquery.min.js');
        ?>
    </body>
</html>
